# Generated by Django 4.1 on 2023-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_todo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.TextField(max_length=255),
        ),
    ]
