# Generated by Django 4.1 on 2023-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
    ]
